//$(document).foundation();
/// header effect ////
"use strict";var last_scroll_pos=0;var scrolling=false;function headerToggle(sPosition){var headerEle=document.querySelector('.region-header');var contentEle=document.getElementById('content');if(sPosition>500){if(!headerEle.classList.contains('header-scroll')){headerEle.classList.add('header-scroll');contentEle.classList.add('content-scroll');}}else if(sPosition<500){if(headerEle.classList.contains('header-scroll')){headerEle.classList.remove('header-scroll');contentEle.classList.remove('content-scroll');}}}function logoToggle(sPosition){var logoEle=document.querySelector('.site-logo');if(sPosition>500){if(!logoEle.classList.contains('logo-scroll')){logoEle.classList.add('logo-scroll');}}else if(sPosition<500){if(logoEle.classList.contains('logo-scroll')){logoEle.classList.remove('logo-scroll');}}}// </ /// header effect //// 
//  Team toggle
function teamBioXfer(){var toggleEle=document.querySelectorAll('.team-trigger');toggleEle.forEach(function(el){el.addEventListener('click',bioXfer);function bioXfer(){// get the team members bio //
ssm.addState({id:'mobile',query:'(min-width: 40em)',onEnter:function onEnter(){deskEffects();},onLeave:function onLeave(){mobileRemoval();}});function mobTog(){alert('mobTog');}function deskEffects(){console.log(el);el.removeEventListener('click',mobTog);var findActive=document.querySelectorAll('.modal-team-bio');findActive.forEach(function(yy){if(yy.classList.contains("active")){yy.classList.remove("active");}});var findTeam=document.querySelectorAll('.team-name');findTeam.forEach(function(xx){if(xx.classList.contains("active")){xx.classList.remove("active");}});var findRole=document.querySelectorAll('.team-role');findRole.forEach(function(zz){if(zz.classList.contains("active")){zz.classList.remove("active");}});var elBio=el.previousElementSibling.textContent;// get the next row element //
//console.log(elBio);
var bioRow=el.parentNode.parentElement.parentElement;///console.log(bioRow);
var bioRowNext=bioRow.nextElementSibling;bioRowNext.textContent=elBio;bioRowNext.classList.toggle("active");//highlight name and role
var teamName=el.parentElement.nextElementSibling;teamName.classList.toggle("active");var teamRole=teamName.nextElementSibling;teamRole.classList.toggle("active");}//deskeffects
function mobileRemoval(){var findActive=document.querySelectorAll('.modal-team-bio');findActive.forEach(function(yy){if(yy.classList.contains("active")){yy.classList.remove("active");}});var findTeam=document.querySelectorAll('.team-name');findTeam.forEach(function(xx){if(xx.classList.contains("active")){xx.classList.remove("active");}});var findRole=document.querySelectorAll('.team-role');findRole.forEach(function(zz){if(zz.classList.contains("active")){zz.classList.remove("active");}});var untoggleEle=document.querySelectorAll('.team-trigger');untoggleEle.forEach(function(tt){tt.removeEventListener('click',bioXfer);});var mobileToggleEle=document.querySelectorAll('.team-trigger');mobileToggleEle.forEach(function(uu){uu.addEventListener('click',mobTog);});}//mobileRemoval
}//bioXfer         
});}window.onload=teamBioXfer;window.onscroll=function(){last_scroll_pos=window.pageYOffset;if(!scrolling){window.requestAnimationFrame(function(){headerToggle(last_scroll_pos);logoToggle(last_scroll_pos);scrolling=false;});}scrolling=true;};