/// this library is loaded via the view template //
'use strict';// NodeList.forEach Polyfill
if(window.NodeList&&!NodeList.prototype.forEach){NodeList.prototype.forEach=function(callback,thisArg){thisArg=thisArg||window;for(var i=0;i<this.length;i++){callback.call(thisArg,this[i],i,this);}};}window.onload=teamBioXfer;function teamBioXfer(){// using simple state manager to toggle desktop and mobile functions
ssm.addState({id:'desk',query:'(min-width: 40em)',onEnter:function onEnter(){teamEffect.deskEffect();//console.log('desk effect called');
}});ssm.addState({id:'mobile',query:'(max-width: 40em)',onEnter:function onEnter(){teamEffect.mobileEffect();}});}var teamEffect={teamTriggers:document.querySelectorAll('.team-trigger'),deskBio:function deskBio(){//this.clearActiveClass;
//this would be the el passed in deskListen for each
//console.log(this);
var findBios=document.querySelectorAll('.modal-team-bio');findBios.forEach(function(yy){if(yy.classList.contains("active")){yy.classList.remove("active");}});var findTeam=document.querySelectorAll('.team-name');findTeam.forEach(function(xx){if(xx.classList.contains("active")){xx.classList.remove("active");}});var findRole=document.querySelectorAll('.team-role');findRole.forEach(function(zz){if(zz.classList.contains("active")){zz.classList.remove("active");}});var elBio=this.previousElementSibling.textContent;// get the next row element //
//console.log(elBio);
var bioRow=this.parentNode.parentElement.parentElement;///console.log(bioRow);
var bioRowNext=bioRow.nextElementSibling;bioRowNext.textContent=elBio;bioRowNext.classList.toggle("active");//highlight name and role
var teamName=this.parentElement.nextElementSibling;teamName.classList.toggle("active");var teamRole=teamName.nextElementSibling;teamRole.classList.toggle("active");},mobBio:function mobBio(){var findTeam=document.querySelectorAll('.team-name');findTeam.forEach(function(xx){if(xx.classList.contains("active")){xx.classList.remove("active");}});var findRole=document.querySelectorAll('.team-role');findRole.forEach(function(zz){if(zz.classList.contains("active")){zz.classList.remove("active");}});var findMobActive=document.querySelectorAll('.team-bio-mobile');findMobActive.forEach(function(yy){if(yy.classList.contains("active")){yy.classList.remove("active");}});var elBio=this.previousElementSibling.textContent;var mobBio=this.parentNode.nextElementSibling.nextElementSibling.nextElementSibling;mobBio.textContent=elBio;mobBio.classList.toggle("active");//highlight name and role
var teamName=this.parentElement.nextElementSibling;console.log(teamName);teamName.classList.toggle("active");var teamRole=teamName.nextElementSibling;console.log(teamRole);teamRole.classList.toggle("active");},deskListen:function deskListen(){var _this=this;console.log('deskListen called');this.teamTriggers.forEach(function(el){el.addEventListener('click',_this.deskBio);});},deskSilence:function deskSilence(){var _this2=this;this.teamTriggers.forEach(function(el){el.removeEventListener('click',_this2.deskBio);});},mobileListen:function mobileListen(){var _this3=this;console.log('mob listen called');this.teamTriggers.forEach(function(el){el.addEventListener('click',_this3.mobBio);});},mobileSilence:function mobileSilence(){var _this4=this;this.teamTriggers.forEach(function(el){el.removeEventListener('click',_this4.mobBio);});},clearActiveClass:function clearActiveClass(){var findBios=document.querySelectorAll('.modal-team-bio');findBios.forEach(function(yy){if(yy.classList.contains("active")){yy.classList.remove("active");}});var findTeam=document.querySelectorAll('.team-name');findTeam.forEach(function(xx){if(xx.classList.contains("active")){xx.classList.remove("active");}});var findRole=document.querySelectorAll('.team-role');findRole.forEach(function(zz){if(zz.classList.contains("active")){zz.classList.remove("active");}});var findMobActive=document.querySelectorAll('.team-bio-mobile');findMobActive.forEach(function(yy){yy.innerHTML="";if(yy.classList.contains("active")){yy.classList.remove("active");}});},// Desktop Function - - - - - - - - - - //
deskEffect:function deskEffect(){this.mobileSilence();this.clearActiveClass();this.deskListen();},// end function deskEffect --- /
// Mobile Function - - - - - - - - - - //
mobileEffect:function mobileEffect(){this.deskSilence();this.clearActiveClass();this.mobileListen();}// end function mobileEffect --- /
};// team effect