<?php

/**
 * @file
 * Contains link_block_element.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function link_block_element_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the link_block_element module.
    case 'help.page.link_block_element':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function link_block_element_theme() {
  $theme = [];
  $theme['link_element'] = [
    'render element' => 'elements',
    'file' => 'link_element.page.inc',
    'template' => 'link_element',
  ];
  $theme['link_element_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'link_element.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function link_block_element_theme_suggestions_link_element(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#link_element'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'link_element__' . $sanitized_view_mode;
  $suggestions[] = 'link_element__' . $entity->bundle();
  $suggestions[] = 'link_element__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'link_element__' . $entity->id();
  $suggestions[] = 'link_element__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
